title: "Rocket.Chat Documentation"
description: Rocket.Chat user, admin, API, integration, plugin and contributing documentation.

# leave trailing slash off
url: https://rocket.chat/docs

# bump if alterting styles or js
version: 41

defaults:
  - scope:
      type: ""
    values:
      layout: "default"

sass:
  style: compressed
  sass_dir: _sass

plugins:
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from

markdown: kramdown

highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
